import 'translation_keys.dart';

const Map<String, String> bnBD = {
  // Common
  TranslationKeys.appName: 'সমবায় সমিতি',
  TranslationKeys.cancel: 'বাতিল',
  TranslationKeys.confirm: 'নিশ্চিত করুন',
  TranslationKeys.retry: 'পুনরায় চেষ্টা করুন',
  TranslationKeys.save: 'সংরক্ষণ',
  TranslationKeys.update: 'আপডেট',
  TranslationKeys.delete: 'মুছে ফেলুন',
  TranslationKeys.seeAll: 'সকল দেখুন',
  TranslationKeys.search: 'অনুসন্ধান করুন...',
  TranslationKeys.filter: 'ফিল্টার',
  TranslationKeys.loading: 'লোড হচ্ছে...',
  TranslationKeys.noDataFound: 'এই মুহূর্তে কোনো তথ্য পাওয়া যায়নি।',

  // Navigation Tabs
  TranslationKeys.tabHome: 'হোম',
  TranslationKeys.tabSavings: 'সঞ্চয় ও ডিপিএস',
  TranslationKeys.tabLoans: 'ঋণ কার্যক্রম',
  TranslationKeys.tabPassbook: 'খতিয়ান বই',
  TranslationKeys.tabProfile: 'প্রোফাইল',

  // Auth & Onboarding
  TranslationKeys.loginTitle: 'স্বাগতম!',
  TranslationKeys.loginSubtitle: 'আপনার সমিতি অ্যাকাউন্টে লগইন করুন',
  TranslationKeys.phoneLabel: 'মোবাইল নম্বর',
  TranslationKeys.phoneHint: '০১XXXXXXXXX',
  TranslationKeys.passwordLabel: 'পাসওয়ার্ড / পিন',
  TranslationKeys.passwordHint: 'পাসওয়ার্ড লিখুন',
  TranslationKeys.rememberMe: 'স্মরণে রাখুন',
  TranslationKeys.forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
  TranslationKeys.loginButton: 'লগইন করুন',
  TranslationKeys.registerPrompt: 'আপনার কি কোনো অ্যাকাউন্ট নেই?',
  TranslationKeys.registerNow: 'সদস্যপদের জন্য আবেদন করুন',
  TranslationKeys.logoutConfirm: 'আপনি কি নিশ্চিত যে লগআউট করতে চান?',
  TranslationKeys.logoutTitle: 'লগআউট',

  // Dashboard & Somiti
  TranslationKeys.totalSavings: 'মোট সঞ্চয় স্থিতি',
  TranslationKeys.activeLoans: 'চলতি ঋণ স্থিতি',
  TranslationKeys.totalShares: 'শেয়ার মূলধন',
  TranslationKeys.memberId: 'সদস্য নং',
  TranslationKeys.quickActions: 'দ্রুত সেবা',
  TranslationKeys.depositMoney: 'টাকা জমা',
  TranslationKeys.payInstallment: 'কিস্তি পরিশোধ',
  TranslationKeys.loanCalculator: 'ঋণ ক্যালকুলেটর',
  TranslationKeys.memberDirectory: 'সদস্য তালিকা',
  TranslationKeys.notices: 'নোটিশ বোর্ড',
  TranslationKeys.recentTransactions: 'সাম্প্রতিক লেনদেন',

  // Savings & DPS
  TranslationKeys.savingsTitle: 'সাধারণ সঞ্চয় হিসাব',
  TranslationKeys.dpsTitle: 'ডিপিএস সঞ্চয় স্কিম',
  TranslationKeys.fdrTitle: 'মেয়াদী আমানত (এফডিআর)',
  TranslationKeys.accountNo: 'হিসাব নম্বর',
  TranslationKeys.maturityDate: 'মেয়াদপূর্তির তারিখ',
  TranslationKeys.monthlyInstallment: 'মাসিক জমা',
  TranslationKeys.depositHistory: 'জমার ইতিহাস',

  // Loans
  TranslationKeys.loanTitle: 'ঋণ পোর্টফোলিও',
  TranslationKeys.loanAmount: 'মঞ্জুরীকৃত ঋণ',
  TranslationKeys.remainingLoan: 'অবশিষ্ট ঋণ',
  TranslationKeys.nextInstallmentDate: 'পরবর্তী কিস্তির তারিখ',
  TranslationKeys.overdueInstallment: 'বকেয়া কিস্তি',
  TranslationKeys.loanRepay: 'কিস্তি প্রদান করুন',

  // Passbook & Transactions
  TranslationKeys.passbookTitle: 'ডিজিটাল পাসবুক',
  TranslationKeys.transactionDetails: 'লেনদেনের বিবরণ',
  TranslationKeys.transactionId: 'ট্রানজেকশন আইডি',
  TranslationKeys.transactionType: 'লেনদেনের ধরন',
  TranslationKeys.transactionDate: 'তারিখ ও সময়',
  TranslationKeys.voucher: 'ডিজিটাল ভাউচার',

  // Profile & Settings
  TranslationKeys.profileTitle: 'সদস্য প্রোফাইল',
  TranslationKeys.personalInfo: 'ব্যক্তিগত তথ্য',
  TranslationKeys.nomineeInfo: 'মনোনীত উত্তরাধিকারী (নমিনি)',
  TranslationKeys.changeLanguage: 'ভাষা পরিবর্তন (Language)',
  TranslationKeys.changePassword: 'পাসওয়ার্ড / পিন পরিবর্তন',
  TranslationKeys.somitiByLaws: 'সমিতির উপ-আইন ও নীতিমালা',
  TranslationKeys.logout: 'লগআউট',

  // Errors & Validations
  TranslationKeys.errorNoInternet: 'ইন্টারনেট সংযোগ পাওয়া যাচ্ছে না। আপনার ইন্টারনেট সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  TranslationKeys.errorServer: 'সার্ভার সাময়িকভাবে অনুপলব্ধ আছে। কিছুক্ষণ পর পুনরায় চেষ্টা করুন।',
  TranslationKeys.errorTimeout: 'অনুরোধের সময় শেষ হয়ে গেছে। পুনরায় চেষ্টা করুন।',
  TranslationKeys.errorSessionExpired: 'আপনার সেশনের মেয়াদ শেষ হয়েছে। অনুগ্রহ করে পুনরায় লগইন করুন।',
  TranslationKeys.errorUnknown: 'একটি অপ্রত্যাশিত ত্রুটি ঘটেছে। পুনরায় চেষ্টা করুন।',
  TranslationKeys.errorCancelled: 'অনুরোধটি বাতিল করা হয়েছে।',
  TranslationKeys.validationPhoneRequired: 'মোবাইল নম্বর প্রদান করা আবশ্যক',
  TranslationKeys.validationPhoneInvalid: 'অনুগ্রহ করে সঠিক ১১ ডিজিটের মোবাইল নম্বর প্রদান করুন',
  TranslationKeys.validationPasswordRequired: 'পাসওয়ার্ড প্রদান করা আবশ্যক',
  TranslationKeys.validationPasswordMinLength: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
  TranslationKeys.validationRequired: 'এই ঘরটি পূরণ করা আবশ্যক',
  TranslationKeys.validationIsRequired: 'প্রদান করা আবশ্যক',
  TranslationKeys.validationAmountRequired: 'টাকার পরিমাণ আবশ্যক',
  TranslationKeys.validationAmountInvalid: 'সঠিক টাকার পরিমাণ লিখুন',
  TranslationKeys.validationAmountMin: 'সর্বনিম্ন পরিমাণ হলো',
  TranslationKeys.validationAmountMax: 'সর্বোচ্চ পরিমাণ হলো',
  TranslationKeys.validationNidRequired: 'জাতীয় পরিচয়পত্র (NID) নম্বর আবশ্যক',
  TranslationKeys.validationNidInvalid: 'সঠিক জাতীয় পরিচয়পত্র নম্বর দিন (১০, ১৩ বা ১৭ ডিজিট)',

  // Force Update
  TranslationKeys.forceUpdateTitle: 'আপডেট প্রয়োজন',
  TranslationKeys.forceUpdateMessage: 'অ্যাপ্লিকেশনটির একটি নতুন সংস্করণ উপলব্ধ রয়েছে। চালিয়ে যেতে অনুগ্রহ করে অ্যাপ্লিকেশনটি আপডেট করুন।',
  TranslationKeys.updateNow: 'এখনই আপডেট করুন',

  // Member API errors
  TranslationKeys.errorForbidden: 'এটি দেখার অনুমতি নেই। অনুগ্রহ করে আবার লগইন করুন।',
  TranslationKeys.errorNotFound: 'পাওয়া যায়নি।',
  TranslationKeys.errorConflict: 'এটি আগেই অন্য তথ্যসহ জমা হয়েছে।',
  TranslationKeys.errorTooMany: 'অনেকবার চেষ্টা হয়েছে। এক মিনিট পরে আবার চেষ্টা করুন।',

  // Member sign-in
  TranslationKeys.errorTitle: 'ত্রুটি',
  TranslationKeys.successTitle: 'সম্পন্ন',
  TranslationKeys.passwordHelp: 'পাসওয়ার্ড সমিতির অফিস দেয়। পাসওয়ার্ড না থাকলে অফিসে যোগাযোগ করুন।',
  TranslationKeys.usePassword: 'পাসওয়ার্ড',
  TranslationKeys.useCode: 'এসএমএস কোড',
  TranslationKeys.codeLabel: 'এসএমএস কোড',
  TranslationKeys.codeHint: '৬ অঙ্কের কোড',
  TranslationKeys.sendCode: 'কোড পাঠান',
  TranslationKeys.resendIn: '@seconds সেকেন্ড পরে আবার পাঠান',
  TranslationKeys.codeRequired: 'এসএমএসে আসা কোডটি লিখুন।',

  // Member sign-in (code)
  TranslationKeys.codeSent: 'এসএমএসে একটি কোড পাঠানো হয়েছে।',

  // Unsupported
  TranslationKeys.errorNotSupported: 'এটি এখন পাওয়া যায় না। সমিতির অফিসে যোগাযোগ করুন।',

  // Month names
  TranslationKeys.month1: 'জানুয়ারি',
  TranslationKeys.month2: 'ফেব্রুয়ারি',
  TranslationKeys.month3: 'মার্চ',
  TranslationKeys.month4: 'এপ্রিল',
  TranslationKeys.month5: 'মে',
  TranslationKeys.month6: 'জুন',
  TranslationKeys.month7: 'জুলাই',
  TranslationKeys.month8: 'আগস্ট',
  TranslationKeys.month9: 'সেপ্টেম্বর',
  TranslationKeys.month10: 'অক্টোবর',
  TranslationKeys.month11: 'নভেম্বর',
  TranslationKeys.month12: 'ডিসেম্বর',

  // Home
  TranslationKeys.homeSavings: 'সঞ্চয়',
  TranslationKeys.homeAdvance: 'অগ্রিম জমা',
  TranslationKeys.homeOutstanding: 'বকেয়া',
  TranslationKeys.homePaidThrough: 'পরিশোধিত',
  TranslationKeys.homePaidThroughNone: 'এখনো কোনো মাস পুরো পরিশোধ হয়নি',
  TranslationKeys.homeAdvanceEstimate: 'অগ্রিম দিয়ে আনুমানিক আরও @months মাস চলবে (বর্তমান হারে)',
  TranslationKeys.homeShares: 'শেয়ার',
  TranslationKeys.homeSharesCount: '@count টি শেয়ার',
  TranslationKeys.homePayNow: 'এখন পরিশোধ করুন',
  TranslationKeys.homeRecentPayments: 'সাম্প্রতিক পরিশোধ',
  TranslationKeys.homeNoPayments: 'এখনো কোনো পরিশোধ নেই।',
  TranslationKeys.memberNo: 'সদস্য নং',

  // Notifications
  TranslationKeys.notificationsTitle: 'বার্তা',

  // Dues
  TranslationKeys.tabDues: 'বকেয়া',
  TranslationKeys.duesTitle: 'আমার বকেয়া',
  TranslationKeys.duesFilterOpen: 'অপরিশোধিত',
  TranslationKeys.duesFilterAll: 'সব',
  TranslationKeys.duesFilterSettled: 'পরিশোধিত',
  TranslationKeys.duesTypeAll: 'সব ধরন',
  TranslationKeys.duesTypeDeposit: 'মাসিক জমা',
  TranslationKeys.duesTypeService: 'সার্ভিস চার্জ',
  TranslationKeys.duesTypeRegistration: 'ভর্তি ফি',
  TranslationKeys.duesTypeLateFee: 'বিলম্ব ফি',
  TranslationKeys.duesAmount: 'পরিমাণ',
  TranslationKeys.duesPaid: 'পরিশোধিত',
  TranslationKeys.duesOutstanding: 'বাকি',
  TranslationKeys.duesDueDate: 'শেষ তারিখ',
  TranslationKeys.duesNoneOpen: 'কোনো বকেয়া নেই।',
  TranslationKeys.duesNone: 'কোনো বকেয়া পাওয়া যায়নি।',

  // Payments
  TranslationKeys.tabPayments: 'পরিশোধ',
  TranslationKeys.paymentsTitle: 'আমার পরিশোধ',
  TranslationKeys.paymentsFilterAll: 'সব',
  TranslationKeys.paymentsFilterPending: 'অপেক্ষমাণ',
  TranslationKeys.paymentsFilterApproved: 'অনুমোদিত',
  TranslationKeys.paymentsFilterRejected: 'বাতিল',
  TranslationKeys.paymentsNone: 'এখনো কোনো পরিশোধ নেই।',
  TranslationKeys.paymentsPayOnline: 'অনলাইনে পরিশোধ',
  TranslationKeys.paymentDetailTitle: 'পরিশোধের বিবরণ',
  TranslationKeys.paymentAmount: 'পরিমাণ',
  TranslationKeys.paymentMethod: 'মাধ্যম',
  TranslationKeys.paymentTrx: 'লেনদেন নম্বর (TrxID)',
  TranslationKeys.paymentDate: 'তারিখ',
  TranslationKeys.paymentApprovedAt: 'অনুমোদনের সময়',
  TranslationKeys.paymentRejectionReason: 'কারণ',
  TranslationKeys.paymentAllocations: 'এই টাকায় যা পরিশোধ হয়েছে',
  TranslationKeys.paymentToAdvance: 'অগ্রিম হিসেবে জমা',
  TranslationKeys.paymentPendingNote: 'সমিতির অফিস যাচাই করে এই পরিশোধ অনুমোদন করবে।',
  TranslationKeys.paymentReceipt: 'রসিদ',
  TranslationKeys.paymentReceiptOpenFailed: 'রসিদ খোলা যায়নি।',
  TranslationKeys.payTitle: 'অনলাইনে পরিশোধ',
  TranslationKeys.payIntro: 'প্রথমে বিকাশ বা নগদে টাকা পাঠান, তারপর এখানে তথ্য দিন।',
  TranslationKeys.payMethod: 'যে মাধ্যমে পাঠিয়েছেন',
  TranslationKeys.payBkash: 'বিকাশ',
  TranslationKeys.payNagad: 'নগদ',
  TranslationKeys.payAmount: 'টাকার পরিমাণ (৳)',
  TranslationKeys.payAmountHint: 'যেমন ১০০০',
  TranslationKeys.payTrx: 'লেনদেন নম্বর (TrxID)',
  TranslationKeys.payTrxHint: 'বিকাশ/নগদের মেসেজে পাবেন',
  TranslationKeys.payDate: 'পাঠানোর তারিখ',
  TranslationKeys.payProof: 'প্রমাণ (স্ক্রিনশট বা পিডিএফ)',
  TranslationKeys.payProofChoose: 'ফাইল বাছাই করুন',
  TranslationKeys.payProofTooLarge: 'ফাইলটি ২ এমবি বা তার কম হতে হবে।',
  TranslationKeys.payProofRequired: 'পরিশোধের প্রমাণ যুক্ত করুন।',
  TranslationKeys.payConfirmTitle: 'এই পরিশোধ পাঠাবেন?',
  TranslationKeys.paySend: 'পাঠান',
  TranslationKeys.paySent: 'পরিশোধ অনুমোদনের জন্য পাঠানো হয়েছে।',

  // Statement
  TranslationKeys.statementTitle: 'খতিয়ান বই',
  TranslationKeys.statementRange: '@from – @until',
  TranslationKeys.statementChangeRange: 'তারিখ বদলান',
  TranslationKeys.statementOpening: 'শুরুর জের',
  TranslationKeys.statementClosing: 'শেষ জের',
  TranslationKeys.statementCharges: 'মোট ধার্য',
  TranslationKeys.statementPaid: 'মোট পরিশোধ',
  TranslationKeys.statementCharge: 'ধার্য',
  TranslationKeys.statementPayment: 'পরিশোধ',
  TranslationKeys.statementBalance: 'জের',
  TranslationKeys.statementNoRows: 'এই সময়ে কোনো ধার্য বা পরিশোধ নেই।',
  TranslationKeys.statementPdf: 'পিডিএফ ডাউনলোড',
  TranslationKeys.statementPdfFailed: 'পিডিএফ খোলা যায়নি।',

  // Shares, messages, profile
  TranslationKeys.sharesTitle: 'আমার শেয়ার',
  TranslationKeys.sharesCurrent: 'এ মাসের শেয়ার',
  TranslationKeys.sharesHistory: 'শেয়ার পরিবর্তন',
  TranslationKeys.sharesFrom: '@month থেকে',
  TranslationKeys.sharesAfter: 'এখন @count টি শেয়ার',
  TranslationKeys.sharesRates: 'এ মাসের হার',
  TranslationKeys.sharesRatesFrom: '@month থেকে চালু হার',
  TranslationKeys.sharesNoRates: 'এ মাসের জন্য এখনো কোনো হার ঠিক হয়নি।',
  TranslationKeys.rateShareUnit: 'প্রতি শেয়ারে মাসিক জমা',
  TranslationKeys.rateServiceCharge: 'প্রতি শেয়ারে সার্ভিস চার্জ',
  TranslationKeys.rateRegistrationFee: 'নতুন প্রতি শেয়ারে ভর্তি ফি',
  TranslationKeys.rateDueDay: 'কিস্তির শেষ তারিখ',
  TranslationKeys.rateDueDayValue: 'প্রতি মাসের @day তারিখ',
  TranslationKeys.rateGraceDays: 'অতিরিক্ত সময়',
  TranslationKeys.rateGraceDaysValue: '@days দিন',
  TranslationKeys.rateLateFee: 'বিলম্ব ফি',
  TranslationKeys.rateLateFeeCap: 'সর্বোচ্চ @amount',
  TranslationKeys.messagesNone: 'এখনো কোনো বার্তা নেই।',
  TranslationKeys.profileDetails: 'আমার তথ্য',
  TranslationKeys.profileNameBn: 'নাম (বাংলা)',
  TranslationKeys.profileNameEn: 'নাম (ইংরেজি)',
  TranslationKeys.profileMobile: 'মোবাইল',
  TranslationKeys.profileJoined: 'সদস্য হওয়ার তারিখ',
  TranslationKeys.profileStatus: 'সদস্যপদ',
  TranslationKeys.profileNoNominees: 'কোনো নমিনি নেই।',
  TranslationKeys.profileEditNote: 'এই তথ্য বদলাতে সমিতির অফিসে যোগাযোগ করুন।',
  TranslationKeys.profileDividends: 'লভ্যাংশ',
  TranslationKeys.profileMessages: 'বার্তা',
  TranslationKeys.profileAboutSomiti: 'সমিতি সম্পর্কে',
  TranslationKeys.dividendsNone: 'এখনো কোনো লভ্যাংশ নেই।',
  TranslationKeys.dividendsShareMonths: '@count শেয়ার-মাস',
  TranslationKeys.somitiRegistration: 'নিবন্ধন নং',
  TranslationKeys.somitiAddress: 'ঠিকানা',
  TranslationKeys.somitiPhone: 'ফোন',
  TranslationKeys.somitiEmail: 'ইমেইল',
  TranslationKeys.passwordCurrent: 'বর্তমান পাসওয়ার্ড',
  TranslationKeys.passwordNew: 'নতুন পাসওয়ার্ড',
  TranslationKeys.passwordConfirm: 'নতুন পাসওয়ার্ড আবার লিখুন',
  TranslationKeys.passwordMismatch: 'দুটি পাসওয়ার্ড মিলছে না।',
  TranslationKeys.passwordSaved: 'পাসওয়ার্ড বদলানো হয়েছে। অন্য ফোনগুলো থেকে লগআউট হয়েছে।',

  // Splash
  TranslationKeys.splashTagline: 'সঞ্চয় ও উন্নয়নের বিশ্বস্ত প্ল্যাটফর্ম',
};
